### ISSUE TITLE
Loading image issue

### ISSUE THREAD

**Issue by wenfangdu** [bartzalewski/grammarly-dark#10]
Hello, I just discovered your awesome plugin, could the document loading image be adjusted as well? 

[This post](https://stackoverflow.com/questions/28963272/how-can-i-inspect-html-element-that-disappears-from-dom-on-lost-focus) might give you some help.

![image](https://user-images.githubusercontent.com/28700378/107192052-12b4b180-6a28-11eb-8250-feed74610cc2.png)

**Comment by bartzalewski** [comment]
Hello @wenfangdu!

I'm very sorry for not fixing that for that long. I'm working on that, thank you so much!
