### ISSUE TITLE
Text Visibility Issue

### ISSUE THREAD

**Issue by PinkSunDev** [bartzalewski/grammarly-dark#13]
Some of the text using this extension is practically impossible to see without hovering over the button, such as those on the left side bar, and in the bottom drop-down box (the one that displays how many words you've typed) Example attached below.
![Capture 1](https://user-images.githubusercontent.com/72238145/112411905-5ad62c00-8d69-11eb-8408-7d88c775a46a.PNG)

**Comment by VVekslyer** [comment]
Yeah having the same issue. Issue appears in Brave latest release, as well as MS Edge latest release.

**Comment by bartzalewski** [comment]
Should be good now.

Thank you!
