### ISSUE TITLE
dosn't work fully

### ISSUE THREAD

**Issue by ArnavByjus** [bartzalewski/grammarly-dark#22]
when I double click for synonymous, or it checks for my grammar, it is still white, it is only dark for the website. please fix this.

**Comment by ArnavByjus** [comment]
test
<img width="218" alt="Screen Shot 2021-10-07 at 2 07 36 PM" src="https://user-images.githubusercontent.com/91581307/136462421-57cae5d4-0ae5-453e-9d65-f09f6423bab2.png">

**Comment by bartzalewski** [comment]
Should be good now.

Thank you!
