### ISSUE TITLE
"correct with assisttant" is white now? 

### ISSUE THREAD

**Issue by V7I0SeventhSector** [bartzalewski/grammarly-dark#23]
![cktgyh fgkuh](https://user-images.githubusercontent.com/86336897/146115897-80975960-0cdf-404f-9eaf-1bfdc6a2f750.PNG)
![iliglu](https://user-images.githubusercontent.com/86336897/146116045-a41036c6-167d-44aa-ac27-db973d83ac1f.PNG)

**Comment by iiiEthos** [comment]
Having the same issue.

**Comment by mirmiragi** [comment]
Same issue here, very distracting.

**Comment by iturpablo** [comment]
Same here :(

**Comment by wagyulamb** [comment]
Also having this issue--would be great if there's a fix. Thank you!

**Comment by bartzalewski** [comment]
Should be good now.

Thank you!

**Comment by mirmiragi** [comment]
> 

Works perfectly now, thanks a ton!
