### ISSUE TITLE
Clarity box readability issue

### ISSUE THREAD

**Issue by wiredin1** [bartzalewski/grammarly-dark#3]
As a Grammarly pro user i use their clarity beta feature quite a lot, I love the extension but it makes their suggestions unreadable.
![image](https://user-images.githubusercontent.com/20534333/89705170-d9cc4080-d90f-11ea-8dad-77b21974b5ef.png)

**Comment by bartzalewski** [comment]
Hello!
Sorry for the late response. I'll fix that.

Please let me know if there are more things to fix.
Thank you!

**Comment by wiredin1** [comment]
You're absolutely fine, there was another bug with a similar problem. I'll get back to you later today with details.

**Comment by wiredin1** [comment]
![image](https://user-images.githubusercontent.com/20534333/89954578-38cad780-dbe6-11ea-8a53-f96f5d1e453b.png)
Similar issue with variety suggestions highlight making it very difficult to read the word while writing.

**Comment by bartzalewski** [comment]
Try it now I fixed it.

**Comment by wiredin1** [comment]
Perfect! You've made it so I actually use Grammarly to write in, thank you! I did find one more thing.
![image](https://user-images.githubusercontent.com/20534333/90188429-4b711800-dd70-11ea-8e92-9808e4e8724c.png)
The done box of things like sentence variety. Sorry if this is nit-picky, I just seem to find more boxes the more I write.

**Comment by bartzalewski** [comment]
No worries, because you help me making this extension better!

**Comment by bartzalewski** [comment]
Can you please show me more details on how I could get that box?

**Comment by wiredin1** [comment]
Good question XD I can't seem to get it to pop back up. If I manage to see it again I'll make a note and get back to you. For now, don't worry about it XD

**Comment by wiredin1** [comment]
Okay, I've managed to get it to pop pretty consistently with conciseness alerts. WHen its trying to get you to cut out non-content words.

If you want a quick sentence to test it with:
After the fall of their mighty empire, these once-proud Romans were ultimately held responsible for the crimes of all of their kin and forced into the chains of servitude for generations as retribution.
and then just delete "of all of their kin" when the alert pops up and it _should_ make the bright white box pop up.

**Comment by bartzalewski** [comment]
Roger that!

**Comment by bartzalewski** [comment]
Just fixed that! 😄

**Comment by wiredin1** [comment]
XD im not quite sure what happened but all the boxes are back to being white
![image](https://user-images.githubusercontent.com/20534333/90670277-ce2e2300-e207-11ea-9bf8-801534243354.png)
![image](https://user-images.githubusercontent.com/20534333/90670296-d4240400-e207-11ea-9179-581878caf290.png)
![image](https://user-images.githubusercontent.com/20534333/90670310-dab27b80-e207-11ea-8227-bca026f0181e.png)

**Comment by bartzalewski** [comment]
Damn, got it. I can see that it's not my fault because of the box-shadow is white as well. 😁

**Comment by wiredin1** [comment]
Weeiirrd, XD I wish this stuff was easier to tell what broke it

**Comment by bartzalewski** [comment]
@wiredin1 @AayanTDE Try it now guys, I believe I fixed it. 😊

**Comment by AayanTDE** [comment]
omg i love you
