### ISSUE TITLE
Dark mode error

### ISSUE THREAD

**Issue by Faris999** [bartzalewski/grammarly-dark#4]
There are some issues with the dark mode.

1.  The text on the right bar is not seen properly.
![image](https://user-images.githubusercontent.com/28823677/92352983-8107e780-f109-11ea-97dc-e7fb507e58ad.png)
2. The title and list color is the same as the background 
![image](https://user-images.githubusercontent.com/28823677/92353065-a8f74b00-f109-11ea-82c4-cc342fe13f2e.png)

Thanks!

**Comment by AayanTDE** [comment]
Same for me, and also the word count selection is like that.
![image](https://user-images.githubusercontent.com/34937282/92470198-88a1bc00-f1ef-11ea-892e-1c01c7bdd975.png)

**Comment by bartzalewski** [comment]
Fixed, thank you. Is it ok now?

**Comment by Faris999** [comment]
Thank you so much. It's fixed now. But there's also an issue with the overall text score.
![image](https://user-images.githubusercontent.com/28823677/92570349-00cdb780-f2ac-11ea-9d31-45dc78e4c3c3.png)

**Comment by bartzalewski** [comment]
Oh, I forgot about it, I'll fix it soon. Thank you!

**Comment by bartzalewski** [comment]
I fixed it. Please let me know if I need to improve more things.
