### ISSUE TITLE
Text unreadable

### ISSUE THREAD

**Issue by LabraBell** [bartzalewski/grammarly-dark#5]
Within the "choose a plan" option of Grammarly, the text is almost exactly the same colour as the background, meaning that I cannot see the prices or other information. 
![image](https://user-images.githubusercontent.com/71012962/92590177-ae809c80-f293-11ea-834e-4754ce5bda7d.png)

**Comment by bartzalewski** [comment]
Grammarly Dark currently works only in the Editor. Thank you for sharing that. I don't think I'll support other pages than Dashboard and the editor.
