### ISSUE TITLE
Text which is highlighted to be corrected is unreadable

### ISSUE THREAD

**Issue by AayanTDE** [bartzalewski/grammarly-dark#6]
![image](https://user-images.githubusercontent.com/34937282/92682622-3a550000-f34a-11ea-8b67-b9ced4769b86.png)

**Comment by AayanTDE** [comment]
Same for the red one's
![image](https://user-images.githubusercontent.com/34937282/92682699-725c4300-f34a-11ea-9d1a-0fda8463faad.png)

**Comment by bartzalewski** [comment]
I just updated it. What about now?

**Comment by AayanTDE** [comment]
Hmm, nope, still the same.
