### ISSUE TITLE
Copy/Pasting text to Google Docs or other word processor carries over color formatting

### ISSUE THREAD

**Issue by technicallyalex** [bartzalewski/grammarly-dark#7]
Text copied from the Grammarly editor to another word processor is formatted as white text when pasted.

**Comment by bartzalewski** [comment]
Would you like to show more details on that to help me with fixing that?

**Comment by technicallyalex** [comment]
Sure, what do you need from me?

The issue is the dark mode changes the actual properties of the text color,
and that change is preserved in the formatting of the text when pasted to
another word processor.

**Comment by xd-arsenic** [comment]
Just press Ctrl + Shift + V when pasting, to remove the formatting this extension gives.

**Comment by technicallyalex** [comment]
👍
