### ISSUE TITLE
White boxes

### ISSUE THREAD

**Issue by keewi1003** [bartzalewski/grammarly-dark#9]
![image](https://user-images.githubusercontent.com/74456339/99147258-e278a380-26c2-11eb-9f07-9fe30b905dc5.png)

It is not readable at all

**Comment by Hakhunter** [comment]
Yeah, I am getting this problem as well, it makes Grammarly unusable

**Comment by bartzalewski** [comment]
Thank you @keewi1003. I currently work on the new release of Grammarly Dark, and soon it will be updated. Please tell me if you see any more bugs.

**Comment by keewi1003** [comment]
Aight. I hope it's fixed soon.

**Comment by bartzalewski** [comment]
Updated to 1.0.9, fixed.
